### PR TITLE
Refactored to use Billy instead of BillysBilling

### PR DESCRIPTION
**Pull request by lsolesen**

### CODE REVIEW

**Comment by nicklasmoeller** [comment]
:+1:

Would it be possible to rename the repo as well, in the same run? Just for clarity of course.

**Comment by lsolesen** [comment]
Yeah. Is my next move. Just need to sync it with the Drupal module.

Den lør. 16. apr. 2016 16.38 skrev Nicklas Møller <notifications@github.com

**Comment by henrikkoch** [comment]
Should I be able to download all your code and just place it in an folder on a web server and then it will be running using the current namespacing methodology you have implemented or do does your code have som preconditions (folders and other places to put files and folders). I can't run any files (test) when trying, without it says that some functions can not be found?

**Comment by lsolesen** [comment]
You should open a new issue for this unless it has something to do with the
pull request. Please state in the new issue what functions are missing and
whether you are using an autoloader.
Den 17/04/2016 01.11 skrev "Henrik J. Koch" <notifications@github.com>:

**Pull request merged**
